package hot

import (
	"investgo/internal/core"
	"investgo/internal/core/provider"
)

// hotConstituents stores the maintained US category membership used by hot-list fallback classification.
// S&P 500 and Nasdaq-100 are tracked at the tradable symbol level, so dual-class constituents can make
// the symbol count exceed the category name. US ETF membership is a curated top-100 universe.
var hotConstituents = map[core.HotCategory][]hotSeed{
	core.HotCategoryUSSP500: usStockSeeds(
		"MMM", "AOS", "ABT", "ABBV", "ACN", "ADBE", "AMD", "AES", "AFL", "A", "APD", "ABNB", "AKAM", "ALB", "ARE", "ALGN", "ALLE", "LNT", "ALL", "GOOGL", "GOOG", "MO", "AMZN", "AMCR",
		"AEE", "AEP", "AXP", "AIG", "AMT", "AWK", "AMP", "AME", "AMGN", "APH", "ADI", "AON", "APA", "APO", "AAPL", "AMAT", "APP", "APTV", "ACGL", "ADM", "ARES", "ANET", "AJG", "AIZ",
		"T", "ATO", "ADSK", "ADP", "AZO", "AVB", "AVY", "AXON", "BKR", "BALL", "BAC", "BAX", "BDX", "BRK.B", "BBY", "TECH", "BIIB", "BLK", "BX", "XYZ", "BK", "BA", "BKNG", "BSX", "BMY",
		"AVGO", "BR", "BRO", "BF.B", "BLDR", "BG", "BXP", "CHRW", "CDNS", "CPT", "CPB", "COF", "CAH", "CCL", "CARR", "CVNA", "CASY", "CAT", "CBRE", "CDW", "COR", "CNC", "CNP", "CF",
		"CRL", "SCHW", "CHTR", "CVX", "CMG", "CB", "CHD", "CIEN", "CI", "CINF", "CTAS", "CSCO", "C", "CFG", "CLX", "CME", "CMS", "KO", "CTSH", "COHR", "COIN", "CL", "CMCSA", "FIX", "CAG",
		"COP", "ED", "STZ", "CEG", "COO", "CPRT", "GLW", "CPAY", "CTVA", "CSGP", "COST", "CTRA", "CRH", "CRWD", "CCI", "CSX", "CMI", "CVS", "DHR", "DRI", "DDOG", "DVA", "DECK", "DE",
		"DELL", "DAL", "DVN", "DXCM", "FANG", "DLR", "DG", "DLTR", "D", "DPZ", "DASH", "DOV", "DOW", "DHI", "DTE", "DUK", "DD", "ETN", "EBAY", "SATS", "ECL", "EIX", "EW", "EA", "ELV",
		"EME", "EMR", "ETR", "EOG", "EPAM", "EQT", "EFX", "EQIX", "EQR", "ERIE", "ESS", "EL", "EG", "EVRG", "ES", "EXC", "EXE", "EXPE", "EXPD", "EXR", "XOM", "FFIV", "FDS", "FICO", "FAST",
		"FRT", "FDX", "FIS", "FITB", "FSLR", "FE", "FISV", "F", "FTNT", "FTV", "FOXA", "FOX", "BEN", "FCX", "GRMN", "IT", "GE", "GEHC", "GEV", "GEN", "GNRC", "GD", "GIS", "GM", "GPC",
		"GILD", "GPN", "GL", "GDDY", "GS", "HAL", "HIG", "HAS", "HCA", "DOC", "HSIC", "HSY", "HPE", "HLT", "HD", "HON", "HRL", "HST", "HWM", "HPQ", "HUBB", "HUM", "HBAN", "HII", "IBM", "IEX",
		"IDXX", "ITW", "INCY", "IR", "PODD", "INTC", "IBKR", "ICE", "IFF", "IP", "INTU", "ISRG", "IVZ", "INVH", "IQV", "IRM", "JBHT", "JBL", "JKHY", "J", "JNJ", "JCI", "JPM", "KVUE", "KDP",
		"KEY", "KEYS", "KMB", "KIM", "KMI", "KKR", "KLAC", "KHC", "KR", "LHX", "LH", "LRCX", "LVS", "LDOS", "LEN", "LII", "LLY", "LIN", "LYV", "LMT", "L", "LOW", "LULU", "LITE", "LYB", "MTB",
		"MPC", "MAR", "MRSH", "MLM", "MAS", "MA", "MKC", "MCD", "MCK", "MDT", "MRK", "META", "MET", "MTD", "MGM", "MCHP", "MU", "MSFT", "MAA", "MRNA", "TAP", "MDLZ", "MPWR", "MNST", "MCO",
		"MS", "MOS", "MSI", "MSCI", "NDAQ", "NTAP", "NFLX", "NEM", "NWSA", "NWS", "NEE", "NKE", "NI", "NDSN", "NSC", "NTRS", "NOC", "NCLH", "NRG", "NUE", "NVDA", "NVR", "NXPI", "ORLY",
		"OXY", "ODFL", "OMC", "ON", "OKE", "ORCL", "OTIS", "PCAR", "PKG", "PLTR", "PANW", "PSKY", "PH", "PAYX", "PYPL", "PNR", "PEP", "PFE", "PCG", "PM", "PSX", "PNW", "PNC", "POOL", "PPG",
		"PPL", "PFG", "PG", "PGR", "PLD", "PRU", "PEG", "PTC", "PSA", "PHM", "PWR", "QCOM", "DGX", "Q", "RL", "RJF", "RTX", "O", "REG", "REGN", "RF", "RSG", "RMD", "RVTY", "HOOD", "ROK",
		"ROL", "ROP", "ROST", "RCL", "SPGI", "CRM", "SNDK", "SBAC", "SLB", "STX", "SRE", "NOW", "SHW", "SPG", "SWKS", "SJM", "SW", "SNA", "SOLV", "SO", "LUV", "SWK", "SBUX", "STT", "STLD",
		"STE", "SYK", "SMCI", "SYF", "SNPS", "SYY", "TMUS", "TROW", "TTWO", "TPR", "TRGP", "TGT", "TEL", "TDY", "TER", "TSLA", "TXN", "TPL", "TXT", "TMO", "TJX", "TKO", "TTD", "TSCO", "TT",
		"TDG", "TRV", "TRMB", "TFC", "TYL", "TSN", "USB", "UBER", "UDR", "ULTA", "UNP", "UAL", "UPS", "URI", "UNH", "UHS", "VLO", "VTR", "VLTO", "VRSN", "VRSK", "VZ", "VRTX", "VRT", "VTRS",
		"VICI", "V", "VST", "VMC", "WRB", "GWW", "WAB", "WMT", "DIS", "WBD", "WM", "WAT", "WEC", "WFC", "WELL", "WST", "WDC", "WY", "WSM", "WMB", "WTW", "WDAY", "WYNN", "XEL", "XYL", "YUM",
		"ZBRA", "ZBH", "ZTS",
	),
	core.HotCategoryUSNasdaq: usStockSeeds(
		"ADBE", "AMD", "ABNB", "ALNY", "GOOGL", "GOOG", "AMZN", "AEP", "AMGN", "ADI", "AAPL", "AMAT", "APP", "ARM", "ASML", "TEAM", "ADSK", "ADP", "AXON", "BKR", "BKNG", "AVGO", "CDNS", "CHTR",
		"CTAS", "CSCO", "CCEP", "CTSH", "CMCSA", "CEG", "CPRT", "CSGP", "COST", "CRWD", "CSX", "DDOG", "DXCM", "FANG", "DASH", "EA", "EXC", "FAST", "FER", "FTNT", "GEHC", "GILD", "HON", "IDXX",
		"INSM", "INTC", "INTU", "ISRG", "KDP", "KLAC", "KHC", "LRCX", "LIN", "MAR", "MRVL", "MELI", "META", "MCHP", "MU", "MSFT", "MSTR", "MDLZ", "MPWR", "MNST", "NFLX", "NVDA", "NXPI", "ORLY",
		"ODFL", "PCAR", "PLTR", "PANW", "PAYX", "PYPL", "PDD", "PEP", "QCOM", "REGN", "ROP", "ROST", "STX", "SHOP", "SBUX", "SNPS", "TMUS", "TTWO", "TSLA", "TXN", "TRI", "VRSK", "VRTX", "WMT",
		"WBD", "WDC", "WDAY", "XEL", "ZS",
	),
	core.HotCategoryUSDow: usStockSeeds(
		"MMM", "AXP", "AMGN", "AMZN", "AAPL", "BA", "CAT", "CVX", "CSCO", "KO", "DIS", "GS", "HD", "HON", "IBM", "JNJ", "JPM", "MCD", "MRK", "MSFT", "NKE", "NVDA", "PG", "CRM", "SHW", "TRV",
		"UNH", "VZ", "V", "WMT",
	),
	core.HotCategoryUSETF: usETFSeeds(
		"SPY", "QQQ", "IVV", "VOO", "VTI", "DIA", "IWM", "IWF", "IWD", "VTV", "VUG", "IJH", "IJR", "RSP", "XLF", "XLK", "XLE", "XLV", "XLI", "XLP", "XLY", "XLC", "XLU", "XLB", "XLRE", "VGT",
		"VNQ", "ARKK", "SOXX", "SMH", "KWEB", "FXI", "HACK", "LIT", "TAN", "ICLN", "BITO", "TLT", "IEF", "SHY", "BND", "AGG", "LQD", "HYG", "JNK", "TIP", "EMB", "GLD", "IAU", "SLV", "GDX",
		"GDXJ", "USO", "UNG", "EEM", "EMXC", "VEA", "VWO", "EFA", "IEMG", "INDA", "EWJ", "EWZ", "TQQQ", "SQQQ", "SPXL", "SOXL", "SOXS", "UVXY", "SH", "SDS", "VYM", "SCHD", "DVY", "HDV", "DGRO",
		"JEPI", "JEPQ", "MTUM", "QUAL", "MOAT", "SGOV", "BIL", "SPLG", "SCHX", "SCHB", "VT", "VB", "VBK", "VBR", "VTWO", "IWB", "IWR", "IWP", "SCHG", "SCHV", "IBIT", "FBTC", "BOTZ", "XBI",
	),
}

// usEquitySeedNames maps US stock hot-pool symbols to their fallback English names.
var usEquitySeedNames = map[string]string{
	"AAPL":  "Apple",
	"ABBV":  "AbbVie",
	"ABNB":  "Airbnb",
	"ABT":   "Abbott Laboratories",
	"ACGL":  "Arch Capital Group",
	"ACN":   "Accenture",
	"ADBE":  "Adobe Inc.",
	"ADI":   "Analog Devices",
	"ADM":   "Archer Daniels Midland",
	"ADP":   "Automatic Data Processing",
	"ADSK":  "Autodesk",
	"AEE":   "Ameren",
	"AEP":   "American Electric Power",
	"AES":   "AES Corporation",
	"AFL":   "Aflac",
	"AIG":   "American International Group",
	"AIZ":   "Assurant",
	"AJG":   "Arthur J. Gallagher & Co.",
	"AKAM":  "Akamai Technologies",
	"ALB":   "Albemarle Corporation",
	"ALGN":  "Align Technology",
	"ALL":   "Allstate",
	"ALLE":  "Allegion",
	"ALNY":  "Alnylam Pharmaceuticals",
	"AMAT":  "Applied Materials",
	"AMCR":  "Amcor",
	"AMD":   "Advanced Micro Devices",
	"AME":   "Ametek",
	"AMGN":  "Amgen",
	"AMP":   "Ameriprise Financial",
	"AMT":   "American Tower",
	"AMZN":  "Amazon",
	"ANET":  "Arista Networks",
	"AON":   "Aon plc",
	"AOS":   "A. O. Smith",
	"APA":   "APA Corporation",
	"APD":   "Air Products",
	"APH":   "Amphenol",
	"APO":   "Apollo Global Management",
	"APP":   "AppLovin",
	"APTV":  "Aptiv",
	"ARE":   "Alexandria Real Estate Equities",
	"ARES":  "Ares Management",
	"ARM":   "Arm Holdings",
	"ASML":  "ASML Holding",
	"ATO":   "Atmos Energy",
	"AVB":   "AvalonBay Communities",
	"AVGO":  "Broadcom",
	"AVY":   "Avery Dennison",
	"AWK":   "American Water Works",
	"AXON":  "Axon Enterprise",
	"AXP":   "American Express",
	"AZO":   "AutoZone",
	"BA":    "Boeing",
	"BAC":   "Bank of America",
	"BALL":  "Ball Corporation",
	"BAX":   "Baxter International",
	"BBY":   "Best Buy",
	"BDX":   "Becton Dickinson",
	"BEN":   "Franklin Resources",
	"BF.B":  "Brown-Forman",
	"BG":    "Bunge Global",
	"BIIB":  "Biogen",
	"BK":    "BNY Mellon",
	"BKNG":  "Booking Holdings",
	"BKR":   "Baker Hughes",
	"BLDR":  "Builders FirstSource",
	"BLK":   "BlackRock",
	"BMY":   "Bristol Myers Squibb",
	"BR":    "Broadridge Financial Solutions",
	"BRK.B": "Berkshire Hathaway",
	"BRO":   "Brown & Brown",
	"BSX":   "Boston Scientific",
	"BX":    "Blackstone Inc.",
	"BXP":   "BXP, Inc.",
	"CAG":   "Conagra Brands",
	"CAH":   "Cardinal Health",
	"CARR":  "Carrier Global",
	"CASY":  "Casey's",
	"CAT":   "Caterpillar",
	"CB":    "Chubb Limited",
	"CBRE":  "CBRE Group",
	"CCEP":  "Coca-Cola Europacific Partners",
	"CCI":   "Crown Castle",
	"CCL":   "Carnival",
	"CDNS":  "Cadence Design Systems",
	"CDW":   "CDW Corporation",
	"CEG":   "Constellation Energy",
	"CF":    "CF Industries",
	"CFG":   "Citizens Financial Group",
	"CHD":   "Church & Dwight",
	"CHRW":  "C.H. Robinson",
	"CHTR":  "Charter Communications",
	"CI":    "Cigna",
	"CIEN":  "Ciena",
	"CINF":  "Cincinnati Financial",
	"CL":    "Colgate-Palmolive",
	"CLX":   "Clorox",
	"CMCSA": "Comcast",
	"CME":   "CME Group",
	"CMG":   "Chipotle Mexican Grill",
	"CMI":   "Cummins",
	"CMS":   "CMS Energy",
	"CNC":   "Centene Corporation",
	"CNP":   "CenterPoint Energy",
	"COF":   "Capital One",
	"COHR":  "Coherent Corp.",
	"COIN":  "Coinbase",
	"COO":   "Cooper Companies (The)",
	"COP":   "ConocoPhillips",
	"COR":   "Cencora",
	"COST":  "Costco",
	"CPAY":  "Corpay",
	"CPB":   "Campbell's Company (The)",
	"CPRT":  "Copart",
	"CPT":   "Camden Property Trust",
	"CRH":   "CRH plc",
	"CRL":   "Charles River Laboratories",
	"CRM":   "Salesforce",
	"CRWD":  "CrowdStrike",
	"CSCO":  "Cisco",
	"CSGP":  "CoStar Group",
	"CSX":   "CSX Corporation",
	"CTAS":  "Cintas",
	"CTRA":  "Coterra",
	"CTSH":  "Cognizant",
	"CTVA":  "Corteva",
	"CVNA":  "Carvana",
	"CVS":   "CVS Health",
	"CVX":   "Chevron",
	"DAL":   "Delta Air Lines",
	"DASH":  "DoorDash",
	"DD":    "DuPont",
	"DDOG":  "Datadog",
	"DE":    "Deere & Company",
	"DECK":  "Deckers Brands",
	"DELL":  "Dell Technologies",
	"DG":    "Dollar General",
	"DGX":   "Quest Diagnostics",
	"DHI":   "D. R. Horton",
	"DHR":   "Danaher Corporation",
	"DIS":   "Disney",
	"DLR":   "Digital Realty",
	"DLTR":  "Dollar Tree",
	"DOC":   "Healthpeak Properties",
	"DOV":   "Dover Corporation",
	"DOW":   "Dow Inc.",
	"DPZ":   "Domino's",
	"DRI":   "Darden Restaurants",
	"DTE":   "DTE Energy",
	"DUK":   "Duke Energy",
	"DVA":   "DaVita",
	"DVN":   "Devon Energy",
	"DXCM":  "DexCom",
	"EA":    "Electronic Arts",
	"EBAY":  "eBay Inc.",
	"ECL":   "Ecolab",
	"ED":    "Consolidated Edison",
	"EFX":   "Equifax",
	"EG":    "Everest Group",
	"EIX":   "Edison International",
	"EL":    "Estee Lauder Companies (The)",
	"ELV":   "Elevance Health",
	"EME":   "Emcor",
	"EMR":   "Emerson Electric",
	"EOG":   "EOG Resources",
	"EPAM":  "EPAM Systems",
	"EQIX":  "Equinix",
	"EQR":   "Equity Residential",
	"EQT":   "EQT Corporation",
	"ERIE":  "Erie Indemnity",
	"ES":    "Eversource Energy",
	"ESS":   "Essex Property Trust",
	"ETN":   "Eaton Corporation",
	"ETR":   "Entergy",
	"EVRG":  "Evergy",
	"EW":    "Edwards Lifesciences",
	"EXC":   "Exelon",
	"EXE":   "Expand Energy",
	"EXPD":  "Expeditors International",
	"EXPE":  "Expedia Group",
	"EXR":   "Extra Space Storage",
	"FANG":  "Diamondback Energy",
	"FAST":  "Fastenal",
	"FCX":   "Freeport-McMoRan",
	"FDS":   "FactSet",
	"FDX":   "FedEx",
	"FE":    "FirstEnergy",
	"FER":   "Ferrovial",
	"FFIV":  "F5, Inc.",
	"FICO":  "Fair Isaac",
	"FIS":   "Fidelity National Information Services",
	"FISV":  "Fiserv",
	"FITB":  "Fifth Third Bancorp",
	"FIX":   "Comfort Systems USA",
	"FOX":   "Fox Corporation (Class B)",
	"FOXA":  "Fox Corporation (Class A)",
	"FRT":   "Federal Realty Investment Trust",
	"FSLR":  "First Solar",
	"FTNT":  "Fortinet",
	"FTV":   "Fortive",
	"GD":    "General Dynamics",
	"GDDY":  "GoDaddy",
	"GE":    "GE Aerospace",
	"GEHC":  "GE HealthCare",
	"GEN":   "Gen Digital",
	"GEV":   "GE Vernova",
	"GILD":  "Gilead Sciences",
	"GIS":   "General Mills",
	"GL":    "Globe Life",
	"GLW":   "Corning Inc.",
	"GM":    "General Motors",
	"GNRC":  "Generac",
	"GOOG":  "Alphabet Inc. (Class C)",
	"GOOGL": "Alphabet Inc. (Class A)",
	"GPC":   "Genuine Parts Company",
	"GPN":   "Global Payments",
	"GRMN":  "Garmin",
	"GS":    "Goldman Sachs",
	"GWW":   "W. W. Grainger",
	"HAL":   "Halliburton",
	"HAS":   "Hasbro",
	"HBAN":  "Huntington Bancshares",
	"HCA":   "HCA Healthcare",
	"HD":    "Home Depot",
	"HIG":   "Hartford (The)",
	"HII":   "Huntington Ingalls Industries",
	"HLT":   "Hilton Worldwide",
	"HON":   "Honeywell",
	"HOOD":  "Robinhood Markets",
	"HPE":   "Hewlett Packard Enterprise",
	"HPQ":   "HP Inc.",
	"HRL":   "Hormel Foods",
	"HSIC":  "Henry Schein",
	"HST":   "Host Hotels & Resorts",
	"HSY":   "Hershey Company (The)",
	"HUBB":  "Hubbell Incorporated",
	"HUM":   "Humana",
	"HWM":   "Howmet Aerospace",
	"IBKR":  "Interactive Brokers",
	"IBM":   "IBM",
	"ICE":   "Intercontinental Exchange",
	"IDXX":  "Idexx Laboratories",
	"IEX":   "IDEX Corporation",
	"IFF":   "International Flavors & Fragrances",
	"INCY":  "Incyte",
	"INSM":  "Insmed Incorporated",
	"INTC":  "Intel",
	"INTU":  "Intuit",
	"INVH":  "Invitation Homes",
	"IP":    "International Paper",
	"IQV":   "IQVIA",
	"IR":    "Ingersoll Rand",
	"IRM":   "Iron Mountain",
	"ISRG":  "Intuitive Surgical",
	"IT":    "Gartner",
	"ITW":   "Illinois Tool Works",
	"IVZ":   "Invesco",
	"JBHT":  "J.B. Hunt",
	"JBL":   "Jabil",
	"JCI":   "Johnson Controls",
	"JKHY":  "Jack Henry & Associates",
	"JNJ":   "Johnson & Johnson",
	"JPM":   "JPMorgan Chase",
	"KDP":   "Keurig Dr Pepper",
	"KEY":   "KeyCorp",
	"KEYS":  "Keysight Technologies",
	"KHC":   "Kraft Heinz",
	"KIM":   "Kimco Realty",
	"KKR":   "KKR & Co.",
	"KLAC":  "KLA Corporation",
	"KMB":   "Kimberly-Clark",
	"KMI":   "Kinder Morgan",
	"KO":    "Coca-Cola",
	"KR":    "Kroger",
	"KVUE":  "Kenvue",
	"LDOS":  "Leidos",
	"LEN":   "Lennar",
	"LH":    "Labcorp",
	"LHX":   "L3Harris",
	"LII":   "Lennox International",
	"LIN":   "Linde plc",
	"LITE":  "Lumentum",
	"LLY":   "Lilly (Eli)",
	"LMT":   "Lockheed Martin",
	"LNT":   "Alliant Energy",
	"LOW":   "Lowe's",
	"LRCX":  "Lam Research",
	"LULU":  "Lululemon Athletica",
	"LUV":   "Southwest Airlines",
	"LVS":   "Las Vegas Sands",
	"LYB":   "LyondellBasell",
	"LYV":   "Live Nation Entertainment",
	"MA":    "Mastercard",
	"MAA":   "Mid-America Apartment Communities",
	"MAR":   "Marriott International",
	"MAS":   "Masco",
	"MCD":   "McDonald's",
	"MCHP":  "Microchip Technology",
	"MCK":   "McKesson Corporation",
	"MCO":   "Moody's Corporation",
	"MDLZ":  "Mondelez International",
	"MDT":   "Medtronic",
	"MELI":  "Mercado Libre",
	"MET":   "MetLife",
	"META":  "Meta Platforms",
	"MGM":   "MGM Resorts",
	"MKC":   "McCormick & Company",
	"MLM":   "Martin Marietta Materials",
	"MMM":   "3M",
	"MNST":  "Monster Beverage",
	"MO":    "Altria",
	"MOS":   "Mosaic Company (The)",
	"MPC":   "Marathon Petroleum",
	"MPWR":  "Monolithic Power Systems",
	"MRK":   "Merck",
	"MRNA":  "Moderna",
	"MRSH":  "Marsh McLennan",
	"MRVL":  "Marvell Technology",
	"MS":    "Morgan Stanley",
	"MSCI":  "MSCI Inc.",
	"MSFT":  "Microsoft",
	"MSI":   "Motorola Solutions",
	"MSTR":  "MicroStrategy",
	"MTB":   "M&T Bank",
	"MTD":   "Mettler Toledo",
	"MU":    "Micron Technology",
	"NCLH":  "Norwegian Cruise Line Holdings",
	"NDAQ":  "Nasdaq, Inc.",
	"NDSN":  "Nordson Corporation",
	"NEE":   "NextEra Energy",
	"NEM":   "Newmont",
	"NFLX":  "Netflix, Inc.",
	"NI":    "NiSource",
	"NKE":   "Nike",
	"NOC":   "Northrop Grumman",
	"NOW":   "ServiceNow",
	"NRG":   "NRG Energy",
	"NSC":   "Norfolk Southern",
	"NTAP":  "NetApp",
	"NTRS":  "Northern Trust",
	"NUE":   "Nucor",
	"NVDA":  "Nvidia",
	"NVR":   "NVR, Inc.",
	"NWS":   "News Corp (Class B)",
	"NWSA":  "News Corp (Class A)",
	"NXPI":  "NXP Semiconductors",
	"ODFL":  "Old Dominion Freight Line",
	"OKE":   "Oneok",
	"OMC":   "Omnicom Group",
	"ON":    "ON Semiconductor",
	"ORCL":  "Oracle Corporation",
	"ORLY":  "O'Reilly Automotive",
	"OTIS":  "Otis Worldwide",
	"OXY":   "Occidental Petroleum",
	"PANW":  "Palo Alto Networks",
	"PAYX":  "Paychex",
	"PCAR":  "Paccar",
	"PCG":   "PG&E Corporation",
	"PDD":   "PDD Holdings",
	"PEG":   "Public Service Enterprise Group",
	"PEP":   "PepsiCo",
	"PFE":   "Pfizer",
	"PFG":   "Principal Financial Group",
	"PG":    "Procter & Gamble",
	"PGR":   "Progressive Corporation",
	"PH":    "Parker Hannifin",
	"PHM":   "PulteGroup",
	"PKG":   "Packaging Corporation of America",
	"PLD":   "Prologis",
	"PLTR":  "Palantir Technologies",
	"PM":    "Philip Morris International",
	"PNC":   "PNC Financial Services",
	"PNR":   "Pentair",
	"PNW":   "Pinnacle West Capital",
	"PODD":  "Insulet Corporation",
	"POOL":  "Pool Corporation",
	"PPG":   "PPG Industries",
	"PPL":   "PPL Corporation",
	"PRU":   "Prudential Financial",
	"PSA":   "Public Storage",
	"PSKY":  "Paramount Skydance Corporation",
	"PSX":   "Phillips 66",
	"PTC":   "PTC Inc.",
	"PWR":   "Quanta Services",
	"PYPL":  "PayPal",
	"QCOM":  "Qualcomm",
	"RCL":   "Royal Caribbean Group",
	"REG":   "Regency Centers",
	"REGN":  "Regeneron Pharmaceuticals",
	"RF":    "Regions Financial Corporation",
	"RJF":   "Raymond James Financial",
	"RL":    "Ralph Lauren Corporation",
	"RMD":   "ResMed",
	"ROK":   "Rockwell Automation",
	"ROL":   "Rollins, Inc.",
	"ROP":   "Roper Technologies",
	"ROST":  "Ross Stores",
	"RSG":   "Republic Services",
	"RTX":   "RTX Corporation",
	"RVTY":  "Revvity",
	"SATS":  "EchoStar",
	"SBAC":  "SBA Communications",
	"SBUX":  "Starbucks",
	"SCHW":  "Charles Schwab Corporation",
	"SHOP":  "Shopify",
	"SHW":   "Sherwin-Williams",
	"SJM":   "J.M. Smucker Company (The)",
	"SLB":   "Schlumberger",
	"SMCI":  "Supermicro",
	"SNA":   "Snap-on",
	"SNDK":  "Sandisk",
	"SNPS":  "Synopsys",
	"SO":    "Southern Company",
	"SOLV":  "Solventum",
	"SPG":   "Simon Property Group",
	"SPGI":  "S&P Global",
	"SRE":   "Sempra",
	"STE":   "Steris",
	"STLD":  "Steel Dynamics",
	"STT":   "State Street Corporation",
	"STX":   "Seagate Technology",
	"STZ":   "Constellation Brands",
	"SW":    "Smurfit Westrock",
	"SWK":   "Stanley Black & Decker",
	"SWKS":  "Skyworks Solutions",
	"SYF":   "Synchrony Financial",
	"SYK":   "Stryker Corporation",
	"SYY":   "Sysco",
	"TAP":   "Molson Coors Beverage Company",
	"TDG":   "TransDigm Group",
	"TDY":   "Teledyne Technologies",
	"TEAM":  "Atlassian",
	"TECH":  "Bio-Techne",
	"TEL":   "TE Connectivity",
	"TER":   "Teradyne",
	"TFC":   "Truist Financial",
	"TGT":   "Target Corporation",
	"TJX":   "TJX Companies",
	"TKO":   "TKO Group Holdings",
	"TMO":   "Thermo Fisher Scientific",
	"TMUS":  "T-Mobile US",
	"TPL":   "Texas Pacific Land Corporation",
	"TPR":   "Tapestry, Inc.",
	"TRGP":  "Targa Resources",
	"TRI":   "Thomson Reuters",
	"TRMB":  "Trimble Inc.",
	"TROW":  "T. Rowe Price",
	"TRV":   "Travelers Companies, Inc.",
	"TSCO":  "Tractor Supply",
	"TSLA":  "Tesla, Inc.",
	"TSN":   "Tyson Foods",
	"TT":    "Trane Technologies",
	"TTD":   "Trade Desk (The)",
	"TTWO":  "Take-Two Interactive",
	"TXN":   "Texas Instruments",
	"TXT":   "Textron",
	"TYL":   "Tyler Technologies",
	"UAL":   "United Airlines Holdings",
	"UBER":  "Uber",
	"UDR":   "UDR, Inc.",
	"UHS":   "Universal Health Services",
	"ULTA":  "Ulta Beauty",
	"UNH":   "UnitedHealth Group",
	"UNP":   "Union Pacific Corporation",
	"UPS":   "United Parcel Service",
	"URI":   "United Rentals",
	"USB":   "U.S. Bancorp",
	"VICI":  "Vici Properties",
	"VLO":   "Valero Energy",
	"VLTO":  "Veralto",
	"VMC":   "Vulcan Materials Company",
	"VRSK":  "Verisk Analytics",
	"VRSN":  "Verisign",
	"VRT":   "Vertiv",
	"VRTX":  "Vertex Pharmaceuticals",
	"VST":   "Vistra Corp.",
	"VTR":   "Ventas",
	"VTRS":  "Viatris",
	"VZ":    "Verizon",
	"WAB":   "Wabtec",
	"WAT":   "Waters Corporation",
	"WBD":   "Warner Bros. Discovery",
	"WDAY":  "Workday, Inc.",
	"WDC":   "Western Digital",
	"WEC":   "WEC Energy Group",
	"WELL":  "Welltower",
	"WFC":   "Wells Fargo",
	"WM":    "Waste Management",
	"WMB":   "Williams Companies",
	"WMT":   "Walmart",
	"WRB":   "W. R. Berkley Corporation",
	"WSM":   "Williams-Sonoma, Inc.",
	"WST":   "West Pharmaceutical Services",
	"WTW":   "Willis Towers Watson",
	"WY":    "Weyerhaeuser",
	"WYNN":  "Wynn Resorts",
	"XEL":   "Xcel Energy",
	"XOM":   "ExxonMobil",
	"XYL":   "Xylem Inc.",
	"XYZ":   "Block, Inc.",
	"YUM":   "Yum! Brands",
	"ZBH":   "Zimmer Biomet",
	"ZBRA":  "Zebra Technologies",
	"ZS":    "Zscaler",
	"ZTS":   "Zoetis",
}

func usStockSeeds(symbols ...string) []hotSeed {
	return buildUSSeeds("US-STOCK", symbols)
}

func usETFSeeds(symbols ...string) []hotSeed {
	return buildUSSeeds("US-ETF", symbols)
}

func buildUSSeeds(market string, symbols []string) []hotSeed {
	seeds := make([]hotSeed, 0, len(symbols))
	for _, symbol := range symbols {
		name := symbol
		if market == "US-STOCK" {
			name = provider.FirstNonEmpty(usEquitySeedNames[symbol], symbol)
		}
		seeds = append(seeds, hotSeed{
			Symbol:   symbol,
			Name:     name,
			Market:   market,
			Currency: "USD",
		})
	}
	return seeds
}

func normalizedUSHotSeeds(category core.HotCategory, seeds []hotSeed) []hotSeed {
	if len(seeds) == 0 {
		return nil
	}

	excluded := map[string]struct{}{}
	switch category {
	case core.HotCategoryUSNasdaq:
		excluded["GOOG"] = struct{}{}
	case core.HotCategoryUSSP500:
		excluded["FOX"] = struct{}{}
		excluded["NWS"] = struct{}{}
	}

	out := make([]hotSeed, 0, len(seeds))
	for _, seed := range seeds {
		if _, skip := excluded[seed.Symbol]; skip {
			continue
		}
		out = append(out, seed)
	}
	return out
}

// hkETFConstituents is a curated list of popular HK-listed ETFs.
// Xueqiu's screener API does not support HK ETF type filtering, so we maintain
// this list explicitly and fetch live quotes from Tencent or Xueqiu.
var hkETFConstituents = hkETFSeeds(
	// Broad index ETFs (HK / Hang Seng)
	"02800", "02833", "02828", "03037", "03011", "03010",
	// H-share / China mainland ETFs
	"02823", "02838", "02846", "09834",
	// Hang Seng Tech
	"03067", "03033", "09067", "03088",
	// MSCI / global equity ETFs
	"03032", "03053", "02801", "03193", "03141",
	// US-tracking ETFs listed in HK
	"03077", "03070", "07288", "07261",
	// Commodity / Gold
	"02840", "83188", "82800",
	// Bond / fixed income
	"03127", "03116", "02813",
	// Sector / thematic
	"03005", "03003", "03015", "02806", "03002", "03110", "03100",
	// Leveraged / inverse
	"07500", "07200", "07226", "07333", "07552", "07522",
	// Southbound / dual-counter / currency hedged
	"83012", "09033", "09837", "82828",
	// Fixed-income / money-market
	"09003", "03009", "03019", "03024", "03034", "03039", "03049",
	// Additional broad market / multi-asset ETFs
	"02836", "02843", "02810", "02821", "02826", "02866",
	// Misc popular ETFs
	"09022", "09069", "09074", "09086", "09115", "09141",
	"09167", "09169", "09173", "09186", "09191", "09439",
	"03006", "03007", "03058", "03060",
)

// hkETFSeeds builds hotSeed entries for HK-listed ETFs from bare 5-digit codes.
func hkETFSeeds(codes ...string) []hotSeed {
	seeds := make([]hotSeed, 0, len(codes))
	for _, code := range codes {
		seeds = append(seeds, hotSeed{
			Symbol:   code + ".HK",
			Name:     code,
			Market:   "HK-ETF",
			Currency: "HKD",
		})
	}
	return seeds
}
